### ISSUE TITLE
I found a bug 

### ISSUE THREAD

**Issue by andreabono** [crotwell/seisFile#10]
I found a bug in **edu.sc.seis.seisFile.waveserver._WaveServer.java_**.  
You use a _PrintWriter_ to write some message to screen.  
The matter is that PrintWriter is **NOT platform independent** and uses different codes for newline depending on the OS platform. So, when called on MacOSX or Linux it uses "\n" , that is properly interpreted by the _Earthworm Wave Server_, **BUT** when used on MSWindows, it attaches a "\r" as a newline... And the EW WS hangs waiting for the newline... And a timeout exception is raised.   
  
So, int the **getMenu()** method:

```
PrintWriter socketOut = getOut();
socketOut.println("MENU: " + nextReqId + " SCNL");
```

should be replaced by:

`System.out.print("MENU: " + nextReqId + " SCNL\n");`  

Cheers.
Andrea

**Comment by crotwell** [comment]
Fixed in 964b391dd85574dc193c526c9588937925be4a4a

Will be in the next release.

Thanks for the bug report.

**Comment by andreabono** [comment]
How about a new release in a maven repository?

**Comment by crotwell** [comment]
1.8.1 was released a week ago with this fix in it.

**Comment by andreabono** [comment]
Sorry for bothering you...
It works great!!!!  
Thanks!!  
Andre
