### ISSUE TITLE
Problem using seisFIle on Netbeans 11

### ISSUE THREAD

**Issue by andreabono** [crotwell/seisFile#11]
I'm trying to use seisFile in my Maven project in Apache NetBeans 11 using JDK 12 (or 11, the problem starts from version 9).
  
If I add this dependency 

```
<dependency>
    <groupId>edu.sc.seis</groupId>
    <artifactId>seisFile</artifactId>
    <version>1.8.0</version>
</dependency>

```  
 and I try to Run the application, I get the following error:

**Error occurred during initialization of boot layer
java.lang.module.ResolutionException: Modules stax.api and java.xml export package javax.xml.stream to module javafx.baseEmpty**
  
This prevents the usage of seisFile in new Java (or JavaFX) code.  
Can I avoid this trouble?  
Thanks!!  
Andrea

**Comment by crotwell** [comment]
Humm, I do not use Netbeans and so am not sure what causes this. There may be a way to tell netbeans to ignore the javax.xml.stream package within stax.api, but I am not sure how to do that.

Probably a new release of seisFile with an updated woodstox dependency would fix this. I will try to get that out soon.

**Comment by crotwell** [comment]
Please try version 1.8.1 and see if it helps, I updated to the latest woodstox which hopefully helps with this.

**Comment by andreabono** [comment]
I tried using version 1.8.0 and it works great!!
Thans a lot!!
Andrea
