### ISSUE TITLE
FDSN data query utils pad gaps with 0s

### ISSUE THREAD

**Issue by amkearns-usgs** [crotwell/seisFile#14]
When running the query tool on triggered channels we have found that rather than produce datarecords with gaps, the returned data zero-pads the time between triggered datarecord logs. For many of our purposes, this is undesirable behavior, and we would prefer the gaps be retained as gaps.

**Comment by crotwell** [comment]
Unless there is a major bug I don't know about, there is no zero padding of gaps within seisFile. And without more significantly more details, like an example query and how your code is calling seisFile when this happens, I don't really think I can do much towards figuring this out.

**Comment by jholland-usgs** [comment]
Thanks for the response, pointing you to our code will be inefficient. We will write a small bit of code that reproduces what we are seeing.

**Comment by amkearns-usgs** [comment]
Our apologies: on further examination this was the result of a flaw in our own code. I have managed to find the issue and now the gaps are correctly reflected in our data.
