### ISSUE TITLE
readData does not close miniseed files

### ISSUE THREAD

**Issue by andreabono** [crotwell/seisFile#16]
Il seems like the edu.sc.seis.seisFile **readData** routine does not close the miniseed file after creating it.   

`public void readData() throws SeedFormatException, IOException, SeisFileException { compiled  code }`

Windows locks the file and I can't delete it...  
Am I wrong?

**Comment by crotwell** [comment]
What class are you using? There is more than one readData method in seisFIle, so need some more info to reproduce.

**Comment by andreabono** [comment]
class MSeedQueryClient

**Comment by crotwell** [comment]
MSeedQueryClient is abstract. Are you extending it?

It does not close the output as it can't know if you are finished with it or not, for example you may wish to output the result of multiple queries into the same output stream.

To close it from your class that extends MSeedQueryClient call
```
if (params.getDataOutputStream() != null) {
            params.getDataOutputStream().close();
}
```
