### ISSUE TITLE
Reading Earthworm messages

### ISSUE THREAD

**Issue by andreabono** [crotwell/seisFile#18]
Is there a way to read EW messages to know, for example, when a PICK occurs on a station?  
I can't find any example about that.

Is there a specific service on the Earthworm host thai should be activated?

**Comment by crotwell** [comment]
Recommend you post to the earthworm forum for general questions about earthworm. I can only provide support for my code, seisFile, not for earthworm in general.

http://groups.google.com/group/earthworm_forum
