### ISSUE TITLE
Can I use it on Android devices?

### ISSUE THREAD

**Issue by yanshanshu** [crotwell/seisFile#23]
Hello, we want to use it on the Android system. We found on the official website that the platform supported by version 1.6 does not have Android. I wonder whether the current latest version supports Android system?

**Comment by crotwell** [comment]
Not quite sure what your issue is. Can you give me more details about what the problem is?

**Comment by yanshanshu** [comment]
I want to use Minieed to compress the raw data received by the seismic wave. I saw version 1.6 on the website and the latest version 2.0 on GitHub. But now I don't know how to compress data with Minieed

**Comment by crotwell** [comment]
compression and decompression are in the seedCodec package, here:
https://github.com/crotwell/seedCodec

You can use either the Steim1.encode() or Steim2.encode() methods to compress seismic waveforms.

An example is in a seisFile test case here:
https://github.com/crotwell/seisFile/blob/main/src/test/java/edu/sc/seis/seisFile/mseed/RoundTripMiniSeed.java

**Comment by crotwell** [comment]
also see this example
https://github.com/crotwell/seisFile/blob/main/src/client/java/edu/sc/seis/seisFile/example/WriteMiniSeed.java
