### ISSUE TITLE
Error parsing QuakeML

### ISSUE THREAD

**Issue by andreabono** [crotwell/seisFile#28]
I'm trying to read some QuakeMLs using standard FDSN web services using this routine  

```
public edu.sc.seis.seisFile.fdsnws.quakeml.Event read_single_quakeml(String host, String event_id, boolean include_all_magnitudes, 
            boolean include_all_origins, boolean include_arrivals){
        try {
            FDSNEventQueryParams queryParams = new FDSNEventQueryParams();
            //
            queryParams.setHost(host.replace("http://", ""));
            queryParams.setEventid(event_id);
            queryParams.setIncludeAllMagnitudes(include_all_magnitudes);
            queryParams.setIncludeAllOrigins(include_all_origins);
            queryParams.setIncludeArrivals(include_arrivals);   
            //
            FDSNEventQuerier querier = new FDSNEventQuerier(queryParams);
            Quakeml quakeml = querier.getQuakeML();
            if (!quakeml.checkSchemaVersion()) {
                log_locally_for_bad_format(quakeml);
            }
            //
            if (quakeml.getEventParameters().getEvents().hasNext())
                return quakeml.getEventParameters().getEvents().next(); // <<<<<<<< ERROR HERE!!
            else
                return null;
            //
        } catch (Exception ex) {
//            logs an error....
            return null;
        }
    }
```    
I get an error in the "ERROR HERE" line while attempting to cast the resulting QuakeML to an _edu.sc.seis.seisFile.fdsnws.quakeml.Event_ object.  
The reason is that the resulting QuakeML has **NO LOCATION CODE in the waveformID tag**.  
  
You can try to replicate the error calling:  
http://geofon.gfz-potsdam.de:80/fdsnws/event/1/query?eventid=gfz2023injc&includeallmagnitudes=true&includeallorigins=false&includearrivals=true  
and then trying to cast it to Event.  If you look at the "pick" objects the have no location code.
  
It's great to get an Event object via that cast, so is there a chance to get this thing fixed or solved in any way?

**Comment by andreabono** [comment]
Ok great!!
Thanks a lot!!

**Comment by crotwell** [comment]
2.0.6 published, may take a little time to show up on maven central...

**Comment by andreabono** [comment]
Great news!!
Thanks a lot!!
Andrea


Il Mar 1 Ago 2023, 18:18 Philip Crotwell ***@***.***> ha
scritto:
