### ISSUE TITLE
Parsing GCF Files

### ISSUE THREAD

**Issue by wjfrelo** [crotwell/seisFile#5]
Good day to all. My name is Wyatt Frelot and I am trying to use this library to parse a GCF file. I don't think I understand how to use the library to to do so. 

I would think that perhaps I would start with a GCFBlock and GCFHeader. But, it seems like there would be a simple way to expose the data to this library...and I am not finding it and would appreciate if someone could get me pointed in  the right direction. 

Thanks,

Wyatt

**Comment by crotwell** [comment]
GCFEarthwormExport is an example that reads GCFBlocks from a serial connection, parses them, and then repackages the data as Earthworm TraceBufs. There are some additional complexities when dealing with the serial connection, including needing the latest rxtx jar, org.rxtx:rxtx:2.2.pre2.

Also, see AbstractGCFBlock.read to read a GCFBlock from a DataInput, like a DataInputStream.

While I have used these classes in the past to connect  to a Guralp instrument via serial. I no longer have those instruments and so have don't need for that and have not used the GCF code in a few years.

I think there is another library directly from Guralp (guralp-builder??) that you may also want to look at. I don't have any further knowledge of it, but could be that it does what you need and may have better support.

Good luck.
