### ISSUE TITLE
Support for VirtualNetwork

### ISSUE THREAD

**Issue by dnorgaard-usgs** [crotwell/seisFile#9]
Hi.  Wondering if there is or will be support for IRIS Virtual Network (http://service.iris.edu/irisws/virtualnetwork/1/)?  

Also, do you have an ETA on when next release after 1.7.4 will be available in maven?

**Comment by dnorgaard-usgs** [comment]
Nevermind.  Seems entering the virtual network with the regular IRIS FDSN-WS urls work.

Still would appreciate ETA on next release if available.

**Comment by crotwell** [comment]
Virtual Network is in github, but not in the 1.7.4 release. You can look here:
https://github.com/crotwell/seisFile/tree/master/src/main/java/edu/sc/seis/seisFile/fdsnws/virtualnet

I do not know when I will be able to push out next release, will see if I can find time to do soon.
